name: perseus
description: App Description
modules:
- name: proxy
  language: go1.x
  web: gin
  description: Module description
  functions:
  - name: ExportersFunction
    entry: entry.go
    description: the entry point for the function
